##
#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/tvdgapp_db?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
#    hikari:
#      username: postgres
#      password: postgres123
#      driver-class-name: org.postgresql.Driver
##spring.jpa.hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#  jpa:
#    hibernate:
#      ddl-auto: update

##
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/tvdgapp_db?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
#    username: tvdgapp_db
#    password: Admincontrol
#    driver-class-name: com.mysql.cj.jdbc.Driver

---
##
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydle?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: mydle
    password: Je2iRfXcyZasLmFN
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        connection:
          characterEncoding: utf8mb4
          useUnicode: true
          collation: utf8mb4_unicode_ci
    open-in-view: false
    
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
#spring:
#  jpa:
#    hibernate:
#      ddl-auto: update  # or "validate", "create", "create-drop" based on your needs
#      dialect: org.hibernate.dialect.PostgreSQLDialect
#    show-sql: true  # Optional: Show SQL statements in the console
#  properties:
#    hibernate:
#      format_sql: true  # Optional: Pretty print SQL in the console
#    database: postgresql

---
spring:
  jpa:
   open-in-view: false

---
spring:
  mail:
    host: smtp.zeptomail.com
    port: 465
    username: emailapikey
    password: wSsVR61y/USjX/t6mzGrdrtumQwHVFrxQBx5ilqkuXT4TfnH88c5k0zIV1WvFfJLEzZsHTsU9+l8kU8F0mJajNh4nwwGCSiF9mqRe1U4J3x17qnvhDzDV25bkxWAKI0MwgRrk2RgEMgj+g==
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
            trust: smtp.zeptomail.com
          connectiontimeout: 10000
          timeout: 10000
          writetimeout: 10000
#    default-encoding: UTF-8
#    sender:
#      address: noreply@mydle.com.ng
#  mail:
#    host: smtp.gmail.com
#    password: zvbhyekplqjyfgyo
#    username: aholemmy@gmail.com
#    properties:
#      mail:
#        transport:
#          protocol: smtp
#        smtp:
#          port: 465
#          auth: true
#          starttls:
#            enable: true
#            required: true
#          ssl:
#            enable: true
#            trust: smtp.gmail.com
#          connectiontimeout: 5000
---
config.emailSender: default
config.emailSender.region: us_west_2
logging:
  config: classpath:log4j2-dev.xml

---
logging:
  level:
    org.springframework: DEBUG
---

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


---



---
# URL for REST Countries API
restcountries:
  api:
    url: https://restcountries.com/v3.1


#spring:
#  flyway:
#    enabled: ${ENABLE_FLYWAY:false}
#    baseline-on-migrate: true


---
logging:
  level:
    org:
      apache:
        coyote:
          http11:
            Http11InputBuffer: DEBUG
            Http11Processor: DEBUG

---

purge:
  cron:
    expression: ${EXP_TOKEN_PURGE_CRON_EXP:0 0 5 * * *}

---
#twilio:
#  account_sid: AC04c415017326f061e833f6162349ac67
#  auth_token: 91b3185a35ac970f23268fd2f1dcfab4
#  phone_number: your_twilio_phone_number

---
#DHL Integration Key
dhl:
  api:
    url: https://express.api.dhl.com/mydhlapi/test/shipments
    username: apY7jU6aW0kN6j
    password: W!7rB^9yT!8eM#5g



