##
#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/tvdgapp_db?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
#    hikari:
#      username: postgres
#      password: postgres123
#      driver-class-name: org.postgresql.Driver
##spring.jpa.hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#  jpa:
#    hibernate:
#      ddl-auto: update

##
spring.datasource.url: jdbc:mysql://localhost:3306/tvdgapp_db?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
spring.datasource.username: tvdgapp_db
spring.datasource.password: Admincontrol

#spring.datasource.driver-class-name: com.mysql.jdbc.Driver
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#spring.jpa.hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.hibernate.ddl-auto: update
---
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
spring.jpa.database: mysql
#spring:
#  jpa:
#    hibernate:
#      ddl-auto: update  # or "validate", "create", "create-drop" based on your needs
#      dialect: org.hibernate.dialect.PostgreSQLDialect
#    show-sql: true  # Optional: Show SQL statements in the console
#  properties:
#    hibernate:
#      format_sql: true  # Optional: Pretty print SQL in the console
#    database: postgresql

---
spring:
  jpa:
   open-in-view: false

---
spring:
  # ===============================
  # = MAIL
  # ===============================
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: aholemm@gmail.com
#    password: zvbhyekplqjyfgyo
#    properties:
#      mail:
#        transport:
#          protocol: smtp
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#            required: true
#          ssl:
#            trust: smtp.gmail.com
#          connectiontimeout: 5000
  mail:
    host: smtp.gmail.com
    password: zvbhyekplqjyfgyo
    username: aholemmy@gmail.com
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          port: 465
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
            trust: smtp.gmail.com
          connectiontimeout: 5000
---
config.emailSender: default
config.emailSender.region: us_west_2
logging:
  config: classpath:log4j2-dev.xml

---
logging:
  level:
    org.springframework: DEBUG
---

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


---

secret_key: ${SECRET_KEY:sk_test_0153f4208929412b896c9cd52160e64d3552dd07}
transaction_url: ${TRANSACTION_URL:https://checkout.paystack.com/w8i4mpgepi70l5n}

http_post: ${HTTP_POST:https://api.paystack.co/transaction/initialize}
post_content_type: ${POST_CONTENT_TYPE:application/json}
post_authorization_key: ${POST_AUTHORIZATION_KEY:sk_test_0153f4208929412b896c9cd52160e64d3552dd07}

# client verify_transaction request properties
http_request =${HTTP_REQUEST: https://api.paystack.co/transaction/verify}
request_content_type: ${REQUEST_CONTENT_TYPE:application/json}
request_authorization: ${REQUEST_AUTHORIZATION_KEY:sk_test_0153f4208929412b896c9cd52160e64d3552dd07}

---
spring:
  flyway:
    enabled: ${ENABLE_FLYWAY:false}
    baseline-on-migrate: true


---
logging:
  level:
    org:
      apache:
        coyote:
          http11:
            Http11InputBuffer: DEBUG
            Http11Processor: DEBUG

---

purge:
  cron:
    expression: ${EXP_TOKEN_PURGE_CRON_EXP:0 0 5 * * *}

