package com.tvdgapp.models.wallet;

public enum PaymentProcessor {
    DLE, NIBSS, NEFT, RTGS, INTRA_BANK_TRANSFER, REMITA, PAYSTACK, FLUTTERWAVE, PAGA, QUICKTELLER, ETRANZACT, UNIFIED_PAYMENTS, INTERSWITCH, VISA_QR, MASTERPASS
}
