package com.tvdgapp.models.wallet.transaction;

public enum TransactionCategory {
    FUNDING, SHIPPING, WAREHOUSING, INVENTORY_MANAGEMENT, ORDER_PROCESSING, TRANSPORTATION, PACKAGING, RETURNS_HANDLING, CUSTOMS_BROKERAGE, CONSULTING, STORAGE, FREIGHT, INSURANCE, MISCELLANEOUS, WITHDRAWAL
}
